public enum RequestCode
{
    ADD_STORE,
    REMOVE_PRODUCT,
    BUY,
    SEARCH,
    INIT_MEMORY,
    INIT_BACKUP,
    END_INIT_MEMORY,
    TRANSFER_BACKUP,
    STUB_TEST_1,
    STUB_TEST_2,

    GET_STORES,
    ADD_PRODUCT,
    MANAGE_STOCK,
    RECORD_SALE,
    GET_SALES_BY_STORE_TYPE,
    GET_SALES_BY_PRODUCT_TYPE,
    GET_SALES_BY_STORE
    }
